### ISSUE TITLE
US6: Add Search Result to Word List

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#10]
## Value proposition

As a user/student
I want to to add a word from the search results to my own word list
in order to review it later on.

## Description

![Image](https://github.com/JudithRe/capstone-flashcard-dictionary/assets/64135479/3709d958-0877-4899-9c6c-d0f228ea6f5a)

## Acceptance criteria

- [x] An Add-button is shown on each dictionary entry, that is not in the word list
- [x] The button adds the entry to the list
- [x] The button should be disabled, if the word is already on the list

## Tasks
- [x] Create branch feature/add-result-button
- [x] Create AddButton component
- [x] Create handleAddToDictionary function

Size: S

**Comment by CJAkkuec** [comment]
You may want to include the mention of the feature branch + its name in the tasks, otherwise all good.
