### ISSUE TITLE
US7: Create and connect db

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#12]
## Value proposition

As a user/student
I want to my word data to be presistent,
so that I can look it up when closing and changing the browser.

## Description

I'm thinking of adding a user login and categories later (that's why they are greyed out still)
![Image](https://user-images.githubusercontent.com/64135479/258083408-6a62e80d-2310-477c-a1a0-aeef7338a86c.png)

## Acceptance criteria

- [x] The db is created and connected
- [x] Previous functionality is still available
- [x] Data can be saved and persists

## Tasks

- [x] Create branch feature/connect-db
- [x] Create db on mongoDB
- [x] Connect data and update functions to receive data from db instead of useState
- [x] delete unnecessary useStates

Size: M

**Comment by ekat-br** [comment]
LGTM. Happy Hacking!
