### ISSUE TITLE
US8: Flashcard

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#14]
## Value proposition

As a user/student
I want to be able to study my words as flashcards,
so that I can memorise their meaning.

## Description

![Image](https://user-images.githubusercontent.com/64135479/258402883-88a65b0e-f29f-4034-8374-e5771cd2f62c.png)

## Acceptance criteria

- [x] A "Start" button is shown on the study page
- [x] on click a card with only the Japanese translation is shown.
- [x] clicking that card reveals the meaning and two buttons 
- [x] 1 for "I knew the answer"
- [x] 1 for "I did not know the answer"
- [x] clicking either button shows the next flash card.
- [x] A button to end the session is displayed and redirects to the study overview

## Tasks

- [x] Create a feature branch "feature/FlashcardStudy"
- [x] Create “pages/study/“
- [x] Create a Flashcard component that dynamically renders either just the Japanese text or text and meaning and two buttons
- [x] Create handleFlashcardSubmission function that displays the words one after the other.
- [x] Create "end session" button
- [x] Add "Study" page to the navigation.

Size: XS/S/M/L/XL

**Comment by ekat-br** [comment]
Good User Story, everything clear and understandable. Have fun!
