### ISSUE TITLE
US9: SRS

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#15]
## Value proposition

As a user/student
I want to only study the words that I don't know well enough yet,
so that I can memorise their meaning long-term.

## Description

![Image](https://user-images.githubusercontent.com/64135479/258403300-8ea98037-0e7d-46e7-b02e-1f888a3f058a.png)

## Acceptance criteria

- [x] Cards are only shown in the study tab, when they are "due"
- [x] If a card is marked as correct, it is moved up a stage and shown again when it's due
- [x] If a card is marked as wrong, it is moved down a stage
- [x] If the card has been marked wrong frequently it moves down 2 stages

## Tasks

- [x] Create branch "feature/SRS"
- [x] Create SRS function
- [x] Update Flashcard component so it receives only the words that are due

Size: M/L

**Comment by ekat-br** [comment]
LGTM
