### ISSUE TITLE
US10: Remove Word from List

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#16]
## Value proposition

As a user/student
I want to be able to edit my word list,
so that I can remove words from my list.

## Description

![Image](https://user-images.githubusercontent.com/64135479/258403565-8591c7da-7d5a-48f2-a887-253d798002a8.png)

## Acceptance criteria

- [x] An Edit Button is shown in the word list
- [x] On click a delete button appears on each word
- [x] clicking the button again editing options disappear
- [x] Clicking the delete button removes a word from my list  

## Tasks

- [x] Create branch "featur/remove-word"
- [x] Create Edit button 
- [x] Create useState for Editing List
- [x] Create delete button 
- [x] Create deleteEntry function 

Size: S

**Comment by Roland-Hufnagel** [comment]
Looks good.
