### ISSUE TITLE
US11: Word Detail Page

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#17]
## Value proposition

As a user/student
I want to have a detailed overview for each word,
so that I can get further information and see my study progress.

## Description

![Image](https://user-images.githubusercontent.com/64135479/258403820-c35182d8-24f9-4279-8066-cca60b993671.png)

## Acceptance criteria

- [x] A word details page is shown when I click on a word
- [x] It includes basic word data, study statistics and - if it is a dictionary entry - further info 
- [x] A back button returns me to the word list

## Tasks

- [x] Create branch "feature/word-detail-page"
- [x] Create dynamic entry page using router to display each word
- [x] Create back button 

Size: S/

**Comment by Roland-Hufnagel** [comment]
Looks good
