### ISSUE TITLE
US12: Edit Word Details

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#18]
## Value proposition

As a user/student
I want to be able to edit my own words,
so that I can change information, should I have made a mistake.

## Description

![Image](https://user-images.githubusercontent.com/64135479/258404071-518c0b4f-f0a9-4a63-97eb-1462404c014f.png)

## Acceptance criteria

- [x] On the Word details page an edit button is shown
- [x] OnClick a modal with an entry form with the previous values is shown
- [x] The can be edited
- [x] a "save" button is shown that saves the new data
- [x] A note informs me that the word's study progress will be reset on save

## Tasks

- [x] Create branch "feature/edit-word-details
- [x] Repurpose AddEntryForm to update data
- [x] Create EditModal component that receives form and is dynamically shown via a useState
- [x] Create updateEntry function 

Size: M

**Comment by Roland-Hufnagel** [comment]
Your userstories are clear and good structured. 👍 
The only thing, that is not that elegant, is: In US10 you make a button ``Edit`` that cannot edit but delete Items.  And in this US you again have an ``Edit``Button to do the 'real' editing. That's a bit confusing. Maybe for a better UX you can rename the button of US10 to 'Delete'? It's up to you 🙂
