### ISSUE TITLE
US1: List of Word Entries

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#2]
## Value proposition

As a user/student
I want to see a list of my saved words,
so that I can see the Japanese and English translation of the word side by side.

## Description

![Image](https://user-images.githubusercontent.com/64135479/257229269-0d1f42cf-eaf4-44e1-96dc-ebe1b91d69c4.png)

## Acceptance criteria

- [x] Entries are displayed as cards in a list.
- [x] Each entry contains Japanese and English versions of the word, as well as a reading for the Japanese word.
- [x] The list is scrollable.

## Tasks

- [x] Create a feature branch "feature/EntryList"
- [x] Create structured dummy data.
- [x] Create page "/words.js"
- [x] Create the “EntriesContainer” component to render the list;
- [x] Create the “Entry” component;

Size: S/M/
