### ISSUE TITLE
US13: User Login

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#24]
## Value proposition

As a user/student
I want to be able to login,
so that I can have my personalised study list.

## Description

![Image](https://github.com/JudithRe/capstone-flashcard-dictionary/assets/64135479/e6155ea5-78c6-48a4-a115-500b0ed0e97b)

## Acceptance criteria

- [ ] A sign in page is shown when opening the app
- [ ] It gives you the option for sign in or registration
- [ ] Once authenticated, you're redirected to your personalised homepage/dashboard

## Tasks

- [ ] Create a branch "feature/authentication"
- [ ] Use NextAuth.js and mongoDB to create sign up 

Size: L

**Comment by mbosselmann** [comment]
Hi Judith,
your user story looks good, but I would suggest to split this one in two as these are two features. One user story for implementing the login for username/password and the second user story for implementing the login with GitHub or vice versa. And in your wireframes we can also see a registration option. Is this covered by another user story that is already implemented? 🤔  Then it would be nice to link to this user story. If you want to implement this later and the user cannot register yet, I would recommend to remove this part for now. :)

I hope this does help!

**Comment by JudithRe** [comment]
Thanks you're right. I changed it. 
I have not created the registration option does it make sense to split this into two user stories? And work with dummy data for the login at first? 

I left it in for now.
