### ISSUE TITLE
US2: Add word to my List

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#3]
## Value proposition

As a user/student
I want to be able to add a new word to my word list,
so that I can review it in my list later on.

## Description

![Image](https://user-images.githubusercontent.com/64135479/257230209-88a7b305-60fa-499b-bc12-d03471b6ecd8.png)

## Acceptance criteria

- [x] A title is displayed.
- [x] An entry form is displayed.
- [x] It includes three input fields
- [x] Two are required - Japanese and English -, one is optional -Reading/comment
- [x] It includes a submit button.
- [x] Clicking the submit button, adds a word to the word list, and refocuses on the first field to enable submission of several words in a row.

## Tasks

- [x] Create a feature branch "feature/AddWordForm"
- [x] Create "/Add" page.
- [x] Create the “AddWordForm” component to render the form;
- [x] Prevent default form behaviour and refocus on first field.
- [x] Create handleAddWord function that adds the word to list on submission of the form

Size: S

**Comment by dm-nosov** [comment]
>adds a word to the word list
Will you navigate to the page with the list of words on submit or remain on this page? Is it a separate page of a part of the words list page?

**Comment by CJAkkuec** [comment]
> > adds a word to the word list
> > Will you navigate to the page with the list of words on submit or remain on this page? Is it a separate page of a part of the words list page?

Adding to that: I'd suggest sticking to resetting the form and to forego routing, seeing as how the user may want to add more words one after another. 🤔 But it should be mentioned as part of the AC and Tasks.

**Comment by JudithRe** [comment]
Thank you. I cleared this up in the AC and Tasks :)

**Comment by dm-nosov** [comment]
LGTM!
