### ISSUE TITLE
US15: Word Due on Homepage

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#32]
## Value proposition

As a user/student
I want to be able to see the number of flashcards that I have to study,
so that I can immediately see when I need to revise a word.

## Description

![Image](https://user-images.githubusercontent.com/64135479/260380347-55e94f24-84d5-43ec-84fc-e6fd93eb6e6f.png)

## Acceptance criteria

- [x] A card is shown on the homepage with a count for the number of words you have to study
- [x] Clicking the card takes you to the study section 

## Tasks

- [x] Create a branch "feature/study-display"
- [x] Create a "StudyDisplay" component.
- [x] Create a function that searches for the words that are due in the database 

Size: S

**Comment by ninaassmann** [comment]
LGTM
