### ISSUE TITLE
US14: Create personalised Word Lists

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#33]
## Value proposition

As a user/student
I want to create my own personalised wordlists,
so that I only review my own words.

## Description

![Image](https://user-images.githubusercontent.com/64135479/260384096-788d9c00-8676-4312-b75f-ef2f4a0d5af9.png)

## Acceptance criteria

- [x]  word-lists are connected to the logged in user rather than just having one 

## Tasks

- [x] create branch backend/restructure-db
- [x] create a reference connection between users and words 
- [x] adapt db models accordingly

Size: S

**Comment by ninaassmann** [comment]
LGTM
