### ISSUE TITLE
US16: Categories

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#34]
## Value proposition

As a user/student
I want to be able to create categories for my word lists,
so that I can group and study them in convenient batches.

## Description

![Image](https://user-images.githubusercontent.com/64135479/260388681-a6482366-e8b3-4bde-8b59-a7977d74479f.png)

## Acceptance criteria

- [x] Categories are shown in the word list and on adding or editing a word
- [x] New categories or choose from an existing one. 
- [x] You can delete categories

## Tasks

- [x] Create branch feature/category
- [x] Create a category collection in db and category model 
- [x] Reference category in entry where necessary
- [x] Create Category component for word list that filters the list
- [x] Create delete function

Size: M
