### ISSUE TITLE
US3: Navigation

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#4]
## Value proposition

As a user/student
I want to be able to switch between seeing my word list and adding new words,
so that I can access the word list and the form from each page.

## Description

![Image](https://user-images.githubusercontent.com/64135479/257231789-6b6058ca-6a1d-4701-9e71-e6dc88fed059.png)

## Acceptance criteria

- [x] A Navigation with two anchors is displayed 
- [x] at the bottom of the page on mobile devices
- [x] at the top of the page on desktops
- [x] Clicking the anchors directs the user to the word list or form 

## Tasks

- [x] Create a feature branch "feature/Navigation"
- [x] Create Navigation Component to render the navigation
- [x] Create Layout Component to render the navigation on each page
- [x] Create Breakpoint for mobile, (tablet) and desktop
- [x] Create MainContent wrapper to avoid overlap
 
Size: S

**Comment by Charlotte-Ketteler** [comment]
LGTM. :)
