### ISSUE TITLE
US18: Profile Page

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#44]
## Value proposition

As a user/student
I want to be able to see my overall progress and personal data on my profile page,
so that I can review them.

## Description

![Image](https://user-images.githubusercontent.com/64135479/262604886-4d1b36ff-5660-40e5-af32-6813d4c01a30.png)

## Acceptance criteria

- [x] The profile page is accessible via the navigation 
- [x] username and overall study statistics are shown
- [x]  A log out button is shown

## Tasks

- [x] Create branch feature/profile-page
- [x] Create a userData component to display user data
- [x] Create a StudyStatistics component to display a study overview 
- [x] Create statistics.js in utils to calculate averages etc.
Size: /S/M

**Comment by StanislavOlijnik** [comment]
LGTM!
