### ISSUE TITLE
US4: Search Bar

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#5]
## Value proposition

As a user/student
I want to be able to search for a word in my word list,
so that I can remind myself of the the meaning.

## Description

![Image](https://user-images.githubusercontent.com/64135479/257236637-c09e3a2f-e8f7-4748-bb8a-b409f6fe2344.png)

## Acceptance criteria

- [x] A search bar is displayed.
- [x] It includes a placeholder text and a submit button
- [x] When typing in a word and clicking on the button matching results are shown from my word list OR
- [x] "No results" is shown, if there are no matches
- [x] The search term is displayed before the results as a reference.

## Tasks

- [x] Create a feature branch "feature/SearchBar"
- [x] Create the “SearchBar” component to render the input field and button;
- [x] Create "SearchResult" component that displays the searchedTerm.
- [x] Create handleSearchInput function that returns matching words from the list 
- [x] Reuse EntriesContainer to display the results

Size: S/M

**Comment by CJAkkuec** [comment]
> ... for a word on my word list,

*in

> When typing in a word and clicking on the button
> matching results are shown from my word list OR

I'm a little confused by the formatting of the AC 🤔 ? Is there an accidental line break?

**Comment by JudithRe** [comment]
Fixed. And thank you. Yes, there was an additional line break. Sorry 😳😅
