### ISSUE TITLE
US5: Dictionary Search

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#6]
## Value proposition

As a user/student
I want to be able to search for words in a dictionary,
so that I can look up the meaning of words I don't have in my list or add more words with the same meaning to my list.

## Description

![image](https://github.com/JudithRe/capstone-flashcard-dictionary/assets/64135479/c1a1ce24-1efe-42f8-b740-7f3349824b5a)

## Acceptance criteria

- [x] When searching for a word that is not in my study list, results from a dictionary are shown.
- [x] If there is a result in my word list a button is displayed to search the dictionary

## Tasks

- [x] Create a feature branch "feature/DictionarySearch"
- [x] Fetch dictionary entries in api/dictionary-search
- [x] Use the “EntriesContainer” and "Entry" component to render the list,
- [x] Update handleSearchInput function so that it searches the word list and the dictionary.
- [x] Create DictonarySearchButton component that dynamically renders a search button and an EntriesContainer.

Size: M/L

**Comment by CJAkkuec** [comment]
I think you're trying to sneak an additional feature into this "Dictionary Search". ;) The dictionary search feature and the add search result to dictionary are two different user stories that need to be handled separately.

Also,
> handleAdd**To**Dictionary

Without the 'to' it sounds a little like you're trying to add an entire dictionary, which might very well be the case for a language learning app.

**Comment by JudithRe** [comment]
Oh, you're right. I'll create another US fot this. I removed it here.
[US6](https://github.com/JudithRe/capstone-flashcard-dictionary/issues/10)

**Comment by CJAkkuec** [comment]
> or add more words with the same meaning to my list.

This can go, and we're all set.
